# Generated by Django 4.2.2 on 2023-06-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Dish',
        ),
    ]
